# -*- coding: utf-8 -*-
"""Generation of the Kodi keymap that opens BD Control during playback.

The keymap is written to the user's profile as
`special://profile/keymaps/script.bdcontrol.xml` and only ever touches the
`FullscreenVideo` window, so navigation everywhere else in Kodi is unchanged.

Why a keymap is needed at all: while a Blu-ray menu is active, Kodi hands the
navigation actions - including OK - to the disc, so no key is left that opens
the OSD.  Keymap translation happens *before* the action reaches the player,
so a key mapped to `RunScript(...)` produces a builtin action the disc handler
does not consume, and BD Control gets to open.

Buttons are bound by their raw code (`<key id="...">`) rather than by name.
Kodi merges every keymap section into one map keyed by that numeric code, so a
code captured from a real key press works whatever kind of device sent it -
keyboard, IR remote or CEC - without the button needing a name in the remote
section.
"""
import os

import xbmcvfs

from . import kodiutils
from .kodiutils import localize, log, log_info

KEYMAP_FILENAME = 'script.bdcontrol.xml'

TOGGLE = 'RunScript(script.bdcontrol,action=toggle)'
DISC_MENU = 'PlayerControl(ShowVideoMenu)'
DISC_POPUP_MENU = 'PlayerControl(ShowVideoMenu(popup))'

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by the BD Control addon (script.bdcontrol) - do not edit.

  Assign the buttons in the addon settings instead; this file is rewritten
  whenever an assignment changes.  Delete it (or switch the keymap off in the
  addon settings) to return to Kodi's stock behaviour.
-->
<keymap>
  <FullscreenVideo>
    <keyboard>
"""

FOOTER = """    </keyboard>
  </FullscreenVideo>
</keymap>
"""


def _disc_menu_command():
    """The builtin the disc-menu button should send.

    `PlayerControl(ShowVideoMenu)` is understood by every Kodi build; the
    popup variant only by builds carrying the ShowVideoMenu(popup|top) patch,
    so it is opt-in.
    """
    if kodiutils.get_setting_bool('extended_disc_menus', False):
        return DISC_POPUP_MENU
    return DISC_MENU


class Slot(object):
    """One assignable button: where it is stored and what it triggers."""

    def __init__(self, name, label_id, code_setting, longpress_setting,
                 command):
        self.name = name
        self.label_id = label_id
        self.code_setting = code_setting
        self.longpress_setting = longpress_setting
        self._command = command

    @property
    def label(self):
        return localize(self.label_id)

    @property
    def command(self):
        if callable(self._command):
            return self._command()
        return self._command

    @property
    def code(self):
        """The stored button code, or 0 when nothing is assigned."""
        try:
            return int(kodiutils.get_setting(self.code_setting, '0') or '0')
        except (TypeError, ValueError):
            return 0

    @property
    def longpress(self):
        return kodiutils.get_setting_bool(self.longpress_setting, False)

    def assign(self, code, longpress):
        kodiutils.set_setting(self.code_setting, str(int(code)))
        kodiutils.set_setting_bool(self.longpress_setting, bool(longpress))

    def clear(self):
        kodiutils.set_setting(self.code_setting, '')
        kodiutils.set_setting_bool(self.longpress_setting, False)

    def describe(self):
        if not self.code:
            return '%s: %s' % (self.label, localize(30146))
        press = localize(30143) if self.longpress else localize(30144)
        return '%s: id %d (%s) -> %s' % (self.label, self.code, press,
                                         self.command)


SLOTS = (
    Slot('osd', 30140, 'key_osd_code', 'key_osd_longpress', TOGGLE),
    Slot('discmenu', 30141, 'key_menu_code', 'key_menu_longpress',
         _disc_menu_command),
)


def slot(name):
    """Look up a slot by name, or return None."""
    for entry in SLOTS:
        if entry.name == name:
            return entry
    return None


def assigned_slot_for(code):
    """The slot already using `code`, or None."""
    for entry in SLOTS:
        if entry.code and entry.code == code:
            return entry
    return None


def keymap_dir():
    return xbmcvfs.translatePath('special://profile/keymaps/')


def keymap_path():
    return os.path.join(keymap_dir(), KEYMAP_FILENAME)


def _element(code, command, longpress):
    modifier = ' mod="longpress"' if longpress else ''
    return '      <key id="%d"%s>%s</key>\n' % (code, modifier, command)


def build():
    """Render the keymap XML for the current assignments, or '' when empty."""
    keys = [_element(entry.code, entry.command, entry.longpress)
            for entry in SLOTS if entry.code]
    if not keys:
        return ''
    return HEADER + ''.join(keys) + FOOTER


def read_existing():
    path = keymap_path()
    if not xbmcvfs.exists(path):
        return ''
    handle = xbmcvfs.File(path)
    try:
        return handle.read()
    finally:
        handle.close()


def is_installed():
    return xbmcvfs.exists(keymap_path())


def disabled_copies():
    """Renamed-away copies of our keymap, newest last.

    Keymap Editor renames every other `*.xml` in the keymaps folder to
    `*.xml.bak.N` when it saves, unless its "enable_multifile" setting is on.
    Finding such a file while our keymap is missing is the signature of that
    having happened.
    """
    directory = keymap_dir()
    if not os.path.isdir(directory):
        return []
    prefix = KEYMAP_FILENAME + '.bak'
    return sorted(os.path.join(directory, name)
                  for name in os.listdir(directory)
                  if name.startswith(prefix))


def write(content):
    directory = keymap_dir()
    if not xbmcvfs.exists(directory):
        xbmcvfs.mkdirs(directory)
    handle = xbmcvfs.File(keymap_path(), 'w')
    try:
        handle.write(content)
    finally:
        handle.close()


def remove():
    """Delete the keymap and let Kodi fall back to its own mappings."""
    if is_installed():
        xbmcvfs.delete(keymap_path())
        log_info('removed keymap %s' % keymap_path())
    reload_keymaps()


def reload_keymaps():
    kodiutils.execute_builtin('Action(reloadkeymaps)')


def sync(notify=False):
    """Bring the keymap file in line with the assignments.

    Returns True when the file on disk changed, so the service can stay quiet
    on the (common) settings change that does not affect the keymap.
    """
    wanted = build() if kodiutils.get_setting_bool('keymap_enabled', True) else ''
    current = read_existing()
    if wanted == current:
        log('keymap already up to date')
        return False
    if wanted:
        write(wanted)
        log_info('wrote keymap %s' % keymap_path())
    elif current:
        xbmcvfs.delete(keymap_path())
        log_info('removed keymap %s' % keymap_path())
    reload_keymaps()
    if notify:
        kodiutils.notify(localize(30070) if wanted else localize(30071))
    return True


def clear_assignments():
    """Forget every assigned button and delete the keymap."""
    for entry in SLOTS:
        entry.clear()
    sync()
    kodiutils.notify(localize(30071))


def migrate_old_settings():
    """Carry a button assigned by an earlier version over to the new slots."""
    osd = slot('osd')
    if osd.code:
        return False
    legacy = kodiutils.get_setting('km_custom_code', '')
    try:
        code = int(legacy or '0')
    except (TypeError, ValueError):
        code = 0
    if not code:
        return False
    log_info('migrating button %d from the old custom-key setting' % code)
    osd.assign(code, kodiutils.get_setting_bool('km_longpress_ok', False))
    kodiutils.set_setting('km_custom_code', '')
    return True


def describe():
    """A human readable summary of the assignments, for diagnostics."""
    if not kodiutils.get_setting_bool('keymap_enabled', True):
        return [localize(30073)]
    lines = [entry.describe() for entry in SLOTS]
    if any(entry.code and entry.longpress for entry in SLOTS):
        lines.append('')
        lines.append(localize(30127))
    return lines
