# -*- coding: utf-8 -*-
"""Generation of the Kodi keymap that opens BD Control during playback.

The keymap is written to the user's profile as
`special://profile/keymaps/script.bdcontrol.xml` and only ever touches the
`FullscreenVideo` window, so navigation everywhere else in Kodi is unchanged.

Why a keymap is needed at all: while a Blu-ray menu is active, Kodi hands the
navigation actions - including OK - to the disc, so no key is left that opens
the OSD.  Keymap translation happens *before* the action reaches the player,
so a key mapped to `RunScript(...)` produces a builtin action the disc handler
does not consume, and BD Control gets to open.
"""
import os

import xbmcvfs

from . import kodiutils
from .kodiutils import localize, log, log_info

KEYMAP_FILENAME = 'script.bdcontrol.xml'

TOGGLE = 'RunScript(script.bdcontrol,action=toggle)'
KODI_OSD = 'RunScript(script.bdcontrol,action=osd)'
DISC_MENU = 'PlayerControl(ShowVideoMenu)'
DISC_POPUP_MENU = 'PlayerControl(ShowVideoMenu(popup))'

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by the BD Control addon (script.bdcontrol) - do not edit.

  Change the mappings in the addon settings instead; this file is rewritten
  whenever those settings change.  Delete it (or use "Remove keymap" in the
  addon settings) to return to Kodi's stock behaviour.
-->
<keymap>
  <FullscreenVideo>
"""

FOOTER = """  </FullscreenVideo>
</keymap>
"""


class Mapping(object):
    """One configurable trigger: a setting plus the keys it writes."""

    def __init__(self, setting, keyboard=(), remote=(), command=TOGGLE,
                 longpress=False):
        self.setting = setting
        self.keyboard = keyboard
        self.remote = remote
        self._command = command
        self.longpress = longpress

    @property
    def command(self):
        """The builtin to write; may depend on other settings."""
        if callable(self._command):
            return self._command()
        return self._command

    def enabled(self):
        return kodiutils.get_setting_bool(self.setting, False)


def _disc_menu_command():
    """The disc-menu builtin the Title button should send.

    `PlayerControl(ShowVideoMenu)` is understood by every Kodi build; the
    popup variant only by builds carrying the ShowVideoMenu(popup|top) patch,
    so it is opt-in.
    """
    if kodiutils.get_setting_bool('extended_disc_menus', False):
        return DISC_POPUP_MENU
    return DISC_MENU


# The default trigger is a long press of OK: a short press still reaches the
# disc menu, so navigation keeps working, while holding the button opens the
# BD Control OSD.
MAPPINGS = (
    Mapping('km_longpress_ok', keyboard=('return',), remote=('select',),
            longpress=True),
    Mapping('km_menu', keyboard=('menu',), remote=('menu',)),
    # The Title / Top Menu button most CEC remotes send is the natural home
    # for the disc's own menu, and Kodi ships no remote binding for it.
    Mapping('km_disc_menu', remote=('title',), command=_disc_menu_command),
    Mapping('km_info', keyboard=('i',), remote=('info',)),
    # Kodi's remote section has no context-menu button, so this one is
    # keyboard only (the 'C' key, and remotes that emit it).
    Mapping('km_contextmenu', keyboard=('c',)),
    Mapping('km_longpress_back', keyboard=('backspace',), remote=('back',),
            longpress=True),
    Mapping('km_osd_direct', keyboard=('o',), remote=('display',),
            command=KODI_OSD),
    Mapping('km_stop', keyboard=('x',), remote=('stop',),
            command='PlayerControl(Stop)'),
)


def keymap_dir():
    return xbmcvfs.translatePath('special://profile/keymaps/')


def keymap_path():
    return os.path.join(keymap_dir(), KEYMAP_FILENAME)


def _element(name, command, longpress):
    modifier = ' mod="longpress"' if longpress else ''
    return '      <%s%s>%s</%s>\n' % (name, modifier, command, name)


def _custom_key_element():
    """A `<key id="...">` entry for the button the user picked, or ''.

    Kodi merges every keymap section into a single per-window map keyed by the
    numeric button code, so binding the raw code works no matter which device
    the button came from - which is the point: it does not depend on the
    button having a name in the remote section, nor on long press support.
    """
    from . import learn
    if not kodiutils.get_setting_bool('km_custom', False):
        return ''
    code = learn.custom_code()
    if not code:
        return ''
    return '      <key id="%d">%s</key>\n' % (code, TOGGLE)


def build():
    """Render the keymap XML for the current settings, or '' when empty."""
    keyboard = []
    remote = []
    for mapping in MAPPINGS:
        if not mapping.enabled():
            continue
        for key in mapping.keyboard:
            keyboard.append(_element(key, mapping.command, mapping.longpress))
        for key in mapping.remote:
            remote.append(_element(key, mapping.command, mapping.longpress))
    custom = _custom_key_element()
    if custom:
        keyboard.append(custom)
    if not keyboard and not remote:
        return ''
    body = ''
    if keyboard:
        body += '    <keyboard>\n%s    </keyboard>\n' % ''.join(keyboard)
    if remote:
        body += '    <remote>\n%s    </remote>\n' % ''.join(remote)
    return HEADER + body + FOOTER


def read_existing():
    path = keymap_path()
    if not xbmcvfs.exists(path):
        return ''
    handle = xbmcvfs.File(path)
    try:
        return handle.read()
    finally:
        handle.close()


def is_installed():
    return xbmcvfs.exists(keymap_path())


def write(content):
    directory = keymap_dir()
    if not xbmcvfs.exists(directory):
        xbmcvfs.mkdirs(directory)
    handle = xbmcvfs.File(keymap_path(), 'w')
    try:
        handle.write(content)
    finally:
        handle.close()


def remove():
    """Delete the keymap and let Kodi fall back to its own mappings."""
    if is_installed():
        xbmcvfs.delete(keymap_path())
        log_info('removed keymap %s' % keymap_path())
    reload_keymaps()


def reload_keymaps():
    kodiutils.execute_builtin('Action(reloadkeymaps)')


def sync(notify=False):
    """Bring the keymap file in line with the settings.

    Returns True when the file on disk changed, so the service can stay quiet
    on the (common) settings change that does not affect the keymap.
    """
    wanted = build() if kodiutils.get_setting_bool('keymap_enabled', True) else ''
    current = read_existing()
    if wanted == current:
        log('keymap already up to date')
        return False
    if wanted:
        write(wanted)
        log_info('wrote keymap %s' % keymap_path())
    elif current:
        xbmcvfs.delete(keymap_path())
        log_info('removed keymap %s' % keymap_path())
    reload_keymaps()
    if notify:
        kodiutils.notify(localize(30070) if wanted else localize(30071))
    return True


def install():
    """Explicit "install" from the settings dialog."""
    if not kodiutils.get_setting_bool('keymap_enabled', True):
        kodiutils.set_setting_bool('keymap_enabled', True)
    if not build():
        kodiutils.ok_dialog(localize(30072))
        return
    sync()
    kodiutils.notify(localize(30070))


def uninstall():
    kodiutils.set_setting_bool('keymap_enabled', False)
    remove()
    kodiutils.notify(localize(30071))


def describe():
    """A human readable summary of the active triggers, for diagnostics."""
    lines = []
    if not kodiutils.get_setting_bool('keymap_enabled', True):
        lines.append(localize(30073))
        return lines
    for mapping in MAPPINGS:
        if not mapping.enabled():
            continue
        keys = []
        for key in list(mapping.keyboard) + list(mapping.remote):
            if key not in keys:  # the same name often exists in both sections
                keys.append(key)
        suffix = ' (%s)' % localize(30074) if mapping.longpress else ''
        lines.append('%s%s -> %s' % (', '.join(keys), suffix, mapping.command))
    from . import learn
    if kodiutils.get_setting_bool('km_custom', False) and learn.custom_code():
        lines.append('%s id %d -> %s' % (localize(30124), learn.custom_code(),
                                         TOGGLE))
    if not lines:
        lines.append(localize(30072))
    if any(mapping.longpress and mapping.enabled() for mapping in MAPPINGS):
        lines.append('')
        lines.append(localize(30127))
    return lines
